### ISSUE TITLE
Could not open stream with mplayer

### ISSUE THREAD

**Issue by baudm** [baudm/mplayer.py#15]
Original [issue 12](https://code.google.com/p/python-mplayer/issues/detail?id=12) created by baudm on 2013-01-15T19:52:29.000Z:

<b>What steps will reproduce the problem?</b>
1.Start stream
from mplayer import Player
p = Player()
p.loadfile('http://1live.akacast.akamaistream.net/7/706/119434/v1/gnl.akacast.a$

<b>What is the expected output? What do you see instead?</b>
mplayer: could not connect to socket
mplayer: No such file or directory

<b>What version of the product are you using? On what operating system?</b>
Latest mplayer

**Comment by jappe999** [comment]
I have this problem, but with local files.

Running Ubuntu 16.04 LTS
Python 3.5
