### ISSUE TITLE
pip install error on Ubuntu 14.10

### ISSUE THREAD

**Issue by baudm** [baudm/mplayer.py#19]
Original [issue 16](https://code.google.com/p/python-mplayer/issues/detail?id=16) created by baudm on 2015-03-25T02:00:58.000Z:

<b>What steps will reproduce the problem?</b>
1.sudo pip install mplayer.py

On what operating system?
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION=&quot;Ubuntu 14.10&quot;
NAME=&quot;Ubuntu&quot;
VERSION=&quot;14.10 (Utopic Unicorn)&quot;
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME=&quot;Ubuntu 14.10&quot;
VERSION_ID=&quot;14.10&quot;
HOME_URL=&quot;http://www.ubuntu.com/&quot;
SUPPORT_URL=&quot;http://help.ubuntu.com/&quot;
BUG_REPORT_URL=&quot;http://bugs.launchpad.net/ubuntu/&quot;

<b>Please provide any additional information below.</b>
jack@ubuntu:~/Shared/pyratao$ sudo pip install mplayer.py
Downloading/unpacking mplayer.py
  Downloading mplayer.py-0.7.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/mplayer.py/setup.py) egg_info for package mplayer.py
    Traceback (most recent call last):
      File &quot;&lt;string&gt;&quot;, line 17, in &lt;module&gt;
      File &quot;/tmp/pip_build_root/mplayer.py/setup.py&quot;, line 5, in &lt;module&gt;
        from mplayer import **version**
      File &quot;mplayer/**init**.py&quot;, line 37, in &lt;module&gt;
        from mplayer.core import Player, Step
      File &quot;mplayer/core.py&quot;, line 412, in &lt;module&gt;
        Player.introspect()
      File &quot;mplayer/core.py&quot;, line 308, in introspect
        cls._generate_methods()
      File &quot;mplayer/core.py&quot;, line 292, in _generate_methods
        func = cls._gen_method_func(name, args)
      File &quot;mplayer/core.py&quot;, line 252, in _gen_method_func
        t = mtypes.type_map[arg]
    KeyError: u'2.0-728-g2c378c7-2ubuntu3'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File &quot;&lt;string&gt;&quot;, line 17, in &lt;module&gt;

  File &quot;/tmp/pip_build_root/mplayer.py/setup.py&quot;, line 5, in &lt;module&gt;

```
from mplayer import __version__
```

  File &quot;mplayer/**init**.py&quot;, line 37, in &lt;module&gt;

```
from mplayer.core import Player, Step
```

  File &quot;mplayer/core.py&quot;, line 412, in &lt;module&gt;

```
Player.introspect()
```

  File &quot;mplayer/core.py&quot;, line 308, in introspect

```
cls._generate_methods()
```

  File &quot;mplayer/core.py&quot;, line 292, in _generate_methods

```
func = cls._gen_method_func(name, args)
```

  File &quot;mplayer/core.py&quot;, line 252, in _gen_method_func

```
t = mtypes.type_map[arg]
```

KeyError: u'2.0-728-g2c378c7-2ubuntu3'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/mplayer.py
Storing debug log for failure in /home/jack/.pip/pip.log

**Comment by legionaryu** [comment]
I have this problem too, but then I tryied to install using the setup.py and worked fine.

Thanks for this great lib man!

**Comment by olegantonyan** [comment]
The problem is caused by mplayer2 (in my case)
mplayer.py generate methods based on `mplayer -input cmdlist` output, and mplayer2 adds `MPlayer2 2.0-728-g2c378c7-4+b1 (C) 2000-2012 MPlayer Team` at the bottom of the list. 

The correct solution I guess is to ignore the last line if we are working with mplayer2, or just add try/rescue. I'm going to test mplayer.py + mplayer2 and if everything is ok - submit pr
