### ISSUE TITLE
No stdout signals emitted from mplayer (Windows 7)

### ISSUE THREAD

**Issue by jleaders** [baudm/mplayer.py#21]
When i run the qt4.py example file, two things happen:

1) The video never plays. I had to add `v.player.pause()` just to see it start
2) No stdout signals seem to be emitted. Therefore, the eof is never detected and triggered. I have tested with a debugger

The line of code that seems to break it is: `self._stdout = _StdoutWrapper(handle=stdout)`
When I comment out the stdout wrapper, it works fine.

**Comment by baudm** [comment]
Windows support is really problematic for this kind of project.
Closing this now because Qt4 is now really old.
