### ISSUE TITLE
How to not use -idle mode?

### ISSUE THREAD

**Issue by imfu** [baudm/mplayer.py#27]
Hi, I was trying to use mplayer.py and expect the mplayer process can exit when the music is done. tried to remove "-idle" parameter in the base args, while it didn't work. wondering is there a way to let the mplayer exit when play completes?

Thanks.

**Comment by baudm** [comment]
Idle mode is central to how MPlayer.py works. If you need the behavior you described, you can just use subprocess.call() for one time execution. Why do you need to quit MPlayer by the way?

**Comment by imfu** [comment]
Thanks baudm for you quick response, I'm using mplayer to play a list of items one after another, but will not get the whole list at once, so I need to know when the current item is finished, then to fetch a new item remotely.

**Comment by imfu** [comment]
I have a work around, which is polling the length attribute, when the play item completes, the length will be None. 

I can also sleep(length) to wait it completes, while this is not flexible, since if other thread stops the play, the sleep() will not exit immediately.

**Comment by baudm** [comment]
For that use case, you can instead use one of the Player subclasses which have event loop integration, e.g. [AsyncPlayer](https://github.com/baudm/mplayer.py/wiki/AsyncPlayer) with `asyncore` integration.

Check the sample usage for AsyncPlayer and notice the additional arguments (for more verbose MPlayer responses). With `-msglevel global=6`, MPlayer emits an EOF signal every time it finishes playing a file. You can add a subscriber function to `Player.stdout` and check for the EOF signal.

If you're not using `asyncore`, you can easily write your own glue code for integrating with any event loop, even your own. Take a look at `AsyncPlayer`'s code and the stdout/stderr wrappers in the `misc` package.

**Comment by imfu** [comment]
Sure, thanks for your help!
