### ISSUE TITLE
loop is not working as expected

### ISSUE THREAD

**Issue by imfu** [baudm/mplayer.py#28]
Hi, baudm,
    I encountered 2 issues when trying to use loop parameter to play an item, could you help to take a look?
(1). For local files, e.g., I have a wma file in which I recorded counting from 1, 2, 3, 4.
if I try to loop 3 times, the first 2 times will skip the last seconds of the wma file, it will only count 1, 2, 3. with 4 skipped. and the last time, it can play correctly.
i.e.  loop 3 times, it will count like: 1, 2, 3, 1, 2, 3, 1, 2, 3, 4.

(2) when play **https** links, the loop will not work at all (http link will played in loop), no matter what loop value I set, it will only play once, and print below messages:
[tls @ 00000000017712c0]The TLS connection was non-properly terminated.
[tls @ 00000000017712c0]The specified session has been invalidated for some reason.
[tls @ 00000000017712c0]The specified session has been invalidated for some reason.
[tls @ 00000000017712c0]The specified session has been invalidated for some reason.
[tls @ 00000000017712c0]The specified session has been invalidated for some reason.

I can repro these 2 issues on both windows and ubuntu systems.

Here's my test code:
url = '/tmp/count1to4.wma'
p = Player()
p.loadfile(url)
time.sleep(1)
p.loop = 3
p.pause()

Thanks in advance.

**Comment by baudm** [comment]
This is an MPlayer-specific behavior and doesn't really concern mplayer.py.
Try setting the loop property first before loading a file.
