### ISSUE TITLE
Can't install mplayer wrapper

### ISSUE THREAD

**Issue by Rubenvdijk** [baudm/mplayer.py#30]
So sorry if this is the most dumbest question ever, I am a noob that's has been trying to install this mplayer wrapper all day, and can't seem to get it.

So my steps basically are:
1. Downloaded the wrapper with git.

`git clone https://github.com/baudm/mplayer.py.git`

2. After which I CD't.

`cd mplayer.py`

Than I tried to install:
3. sudo python setup.py install

But I keep getting this error:
> pi@raspberrypi:~/mplayer.py $  python setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 5, in <module>
>     from mplayer import __version__
>   File "/home/pi/mplayer.py/mplayer/__init__.py", line 38, in <module>
>     from mplayer.core import Player, Step
>   File "/home/pi/mplayer.py/mplayer/core.py", line 417, in <module>
>     Player.introspect()
>   File "/home/pi/mplayer.py/mplayer/core.py", line 312, in introspect
>     cls._generate_properties()
>   File "/home/pi/mplayer.py/mplayer/core.py", line 199, in _generate_properties
>     pname, ptype, ptype2, pmin, pmax = line
> ValueError: need more than 1 value to unpack
> 

Could someone please help me with this? I have no clue what to do to fix this.

**Comment by baudm** [comment]
I'll try to fix this tonight. MPlayer's output format has changed that's why the parsing fails. Can you post here the exact version of your MPlayer? Thanks

**Comment by baudm** [comment]
I tried to reproduce this on Ubuntu 17.10 using MPlayer v1.3.0, but it works on this system. Can you provide more info about the MPlayer and RPi OS versions?
