### ISSUE TITLE
noconfig breaks audio detection

### ISSUE THREAD

**Issue by rohdef** [baudm/mplayer.py#31]
Hey, I had an issue with audio detection. I skimmed the network of projects from this one for solutions and found a fork with a solution. Don't know why there isn't a pull request for it, however, changing it in this project solved the problem:

https://github.com/tb0hdan/mplayer.py/commit/a392ca594dfe7a25278881581342b9910ea27ff4

Could we please get this corrected in the official project too?

**Comment by rohdef** [comment]
Dispite that fix, so it now detects pulseaudio as expected on my system the video I'm trying to play is not playing, it just freezes. If you have any ideas for that let me know. I'm using apart from the path to the file the code is identical to: https://github.com/baudm/mplayer.py/wiki/QtPlayer (that is I just copied it and corrected the path). Also seems that it is not exiting correctly when exiting the player

**Comment by baudm** [comment]
Cherry-picked his commit here: https://github.com/baudm/mplayer.py/commit/44da3eccd62430a951eb0660c34bc9f094fb0af6

I think the freezing issue is specific to the MPlayer and PulseAudio interaction and is outside the scope of the wrapper. That said, I'm closing this issue now.
