### ISSUE TITLE
No music playing with known good file and your example code

### ISSUE THREAD

**Issue by mlcassatt** [baudm/mplayer.py#32]
Running 
Mplayer 1.3.0-7
Fedora 26
Python 3.6.2
using your example code:
from mplayer import Player, CmdPrefix

# Set default prefix for all Player instances
Player.cmd_prefix = CmdPrefix.PAUSING_KEEP

# Since autospawn is True by default, no need to call player.spawn() manually
player = Player()

# Play a file
player.loadfile('music/Haunted.mp3')

My file does not play. 
I get the following:
do_connect: could not connect to socket
connect: No such file or directory
But, i get that no matter how I interface with mplayer, so I assume that's normal.

Thank you!

**Comment by baudm** [comment]
Can you play the file using MPlayer directly (i.e. via command line)?

**Comment by nirmalkushwah** [comment]
> Can you play the file using MPlayer directly (i.e. via command line)?

I am having the same issue, I cannot play the song in py script but the same link can be played from the same console.

**Comment by mlcassatt** [comment]
@baudm, I was able to play the file using mplayer directly just fine. I made adjustments and used VLC for my project, but I'm still interested if you figure(d) out what was going on. The error message I showed always occurred when I used mplayer, but the music played when calling directly vs. using mplayer.py.

**Comment by baudm** [comment]
@nirmalkushwah @mlcassatt can you enable verbose mode? Does it also happen with other files?

**Comment by hcombee** [comment]
@baudm, I am having exactly the same issue here, before I even try to load a file I already get the error below. I am running this on an Orange Pi Zero Plus (ARMBIAN 5.65 stable Ubuntu 18.04.1 LTS 4.14.78-sunxi64) 

root@orangepiradio:~/bin# python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mplayer import Player, CmdPrefix
>>> Player.cmd_prefix = CmdPrefix.PAUSING_KEEP
>>> p = Player()
**>>> do_connect: could not connect to socket**
**connect: No such file or directory**

Mplayer itself is working but it shows the same error! 

root@orangepiradio:~/bin# mplayer test.mp3 
MPlayer 1.3.0 (Debian), built with gcc-7 (C) 2000-2016 MPlayer Team
**do_connect: could not connect to socket**
**connect: No such file or directory**
Failed to open LIRC support. You will not be able to use your remote control.

Playing test.mp3.
libavformat version 57.83.100 (external)
Audio only file format detected.
Clip info:
 Title: How How (Single Version)
 Artist: Yello
 Album: HowHow (Black) - Single
 Year: 1994
 Comment:  
 Track: 1
 Genre: Unknown
Load subtitles in ./
==========================================================================
Opening audio decoder: [mpg123] MPEG 1.0/2.0/2.5 layers I, II, III
AUDIO: 44100 Hz, 2 ch, s16le, 320.0 kbit/22.68% (ratio: 40000->176400)
Selected audio codec: [mpg123] afm: mpg123 (MPEG 1.0/2.0/2.5 layers I, II, III)
==========================================================================
AO: [alsa] 44100Hz 2ch s16le (2 bytes per sample)
Video: no video
Starting playback...

**Comment by hcombee** [comment]
Seems like this error message was caused by the fact that lirc was not installed. After installation of lirc the message is gone but it still doesn't play any music

**Comment by kxkayser** [comment]
Hi Darwin.  I don't think my #36 is a duplicate.  In the previous issues, the programs were not running do to socket errors.  My program is running fine and displaying items like artist, length, etc.  There is just no audio.  The same is true when  running from the Python interpreter.  I have also tried sleeping the script to allow time for the item to play.  Please note, that when I added the "Player._base_args = ('-slave',)" statement, I could no longer retrieve attributes, etc.  Here is the current code and output.  Thanks.

#!/usr/bin/env python3

from mplayer import Player, CmdPrefix
import time

# Set default prefix for all Player instances
Player.cmd_prefix = CmdPrefix.PAUSING

Player._base_args = ('-slave',)

# create Player instance
player = Player()

# Play a file
player.loadfile('/home/pi/Music/dc.mp3')

# Get title from metadata
metadata = player.metadata
print (metadata.get('Artist', ''))
print (metadata.get('Title', ''))

# Print the filename
print (player.filename)

#  Print track length
print(player.length)


Output:
pi@raspberrypi:~/pp $ ./mptest.py
Traceback (most recent call last):
  File "./mptest.py", line 19, in <module>
    print (metadata.get('Artist', ''))
AttributeError: 'NoneType' object has no attribute 'get'
pi@raspberrypi:~/pp $

**Comment by baudm** [comment]
@kxkayser the socket errors have nothing to do with mplayer.py and the missing audio. Those are simply messages that MPlayer displays for most configurations.

Re: unable to retrieve attributes, that is expected because the arguments necessary for that to work were not in the base_args. I asked you to try it to be able to isolate the problem (i.e. check which part of the wrapper code is causing the audio bug). Also, you don't need to copy and paste the whole entry from the wiki. I can't tell which code you're referring to.

@all:
Try running MPlayer in the command line with slave mode on:
$ mplayer -slave

Try and load a file by following the commands here: http://www.mplayerhq.hu/DOCS/tech/slave.txt
If there's still no audio, then slave mode is broken and I can't do anything about it.

**Comment by kxkayser** [comment]
Hi Darwin.  Thanks for the response.  -slave mode works fine from the console and I get audio.  Also, I ran the following commands and got audio:

pi@raspberrypi:~/Music $ mkfifo /tmp/fifofile
pi@raspberrypi:~/Music $ mplayer -slave -input file=/tmp/fifofile dc.mp3

Here is a bit of the output:  (audio is playing)
MPlayer 1.3.0 (Debian), built with gcc-6.2.1 (C) 2000-2016 MPlayer Team

Playing dc.mp3.
libavformat version 57.56.101 (external)
Mismatching header version 57.56.100
Audio only file format detected.
Clip info:
 Title: Ready To Run
 Artist: Dixie Chicks
 Album: Fly
 Year: 
 Comment:                             
 Track: 1
 Genre: Other
Load subtitles in ./

**Comment by kxkayser** [comment]
F+Hi Darwin.  Any update on this?  Is there any additional information I can get t you?  Thanks.

**Comment by kxkayser** [comment]
Hi Darwin,

 

Haven’t seen any update on this is several weeks.  Can I help in diagnosing this issue?

 

Thanks,

 

Ken Kayser

Tobaccoville, NC

 

kxkayser@gmail.com

**Comment by wrybread** [comment]
I'm having the same issue in Ubuntu. Running with known good audio file and it works fine from console, but I get no audio with the script below. Interestingly it reads the length of the file in the p.length statement, so I guess it's loading it?

I'm glad to do any tests.

```
import mplayer
import time

p = mplayer.Player()

p.loadfile("test.mp3")

while True:

  time.sleep(1)
  print p.filename
  print p.length

```

**Comment by baudm** [comment]
Hi all, sorry for the long wait. I finally traced the issue and it has something to do with the pause state.
To verify this, after calling loadfile(), try unpausing by calling pause(). The file should immediately play. I'll be releasing 0.7.2 in a bit.

**Comment by wrybread** [comment]
Confirmed, works!

**Comment by baudm** [comment]
Install 0.7.2 via pip:
`$ pip install git+https://github.com/baudm/mplayer.py.git@0.7.2`
