### ISSUE TITLE
Setting cache

### ISSUE THREAD

**Issue by pascollin** [baudm/mplayer.py#33]
Hi,

To play some url, I have to change the mplayer cache option dynamically. 

Is it possible to set the mplayer cache option with mplayer.py (~/.mplayer/config doesn't fit my needs, as it set the same cache for any url)

Thanks

**Comment by baudm** [comment]
If there's a way of specifying it via command line options, then it can be done via mplayer.py. If not, I'm afraid you're out of luck. See [wiki](https://github.com/baudm/mplayer.py/wiki/Player) for details on the extra args.
