### ISSUE TITLE
"args" mplayer options does't work

### ISSUE THREAD

**Issue by bhong2002** [baudm/mplayer.py#38]
***** this is my test does not play:

> import Player
> 
> player = Player()
> player.args=['-vfm', 'ffmpeg', '-autosync', '30', '-mc', '2.0',
>                '-ontop', '-vf', 'scale', '-xy', '640:480', '-panscan', '1',
>                '-cache', '8192', '-ontop']
> 
> if __name__ == "__main__":
>     player.loadfile('*.mkv')

 ***** and this will play:

> import time
> import Player
> 
> player = Player()
> player.args=['-vfm', 'ffmpeg', '-autosync', '30', '-mc', '2.0',
>                '-ontop', '-vf', 'scale', '-xy', '640:480', '-panscan', '1',
>                '-cache', '8192', '-ontop']
> 
> if __name__ == "__main__":
>     player.loadfile('*.mkv')
>     time.sleep(player.length)

and it does not going "-ontop" as mentioned in player.args

> my player version:

CPU vendor name: GenuineIntel  max cpuid level: 22
CPU: Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (Family: 6, Model: 142, Stepping: 10)
extended cpuid-level: 8
extended cache-info: 16801856
Detected cache-line size is 64 bytes
CPUflags:  MMX: 1 MMX2: 1 3DNow: 0 3DNowExt: 0 SSE: 1 SSE2: 1 SSE3: 1 SSSE3: 1 SSE4: 1 SSE4.2: 1 AVX: 1
Compiled with runtime CPU detection.
get_path('codecs.conf') -> 'C:/Program Files/MPlayer/mplayer/codecs.conf'
Reading optional codecs config file C:/Program Files/MPlayer/mplayer/codecs.conf: No such file or directory
Using built-in default codecs.conf.
init_freetype

**Comment by baudm** [comment]
First, please test if MPlayer actually runs with the given options. If it does run, please give more details about what's working and what's not.

**Comment by bhong2002** [comment]
yes .. it can play the file but the given parameters on args . . .  "player.args=['-vfm', 'ffmpeg', '-autosync', '30', '-mc', '2.0',
'-ontop', '-vf', 'scale', '-xy', '640:480', '-panscan', '1',
'-cache', '8192', '-ontop']"  

does not... .. no error message appears... 

eg:.. the "-ontop" option wont work...

**Comment by baudm** [comment]
In the first example, the code will immediately exit after `player.loadfile('*.mkv')` is executed. In your second example, it "works" because execution is blocked for the duration of `time.sleep(player.length)`. Take a look at the `asyncore` integration if you want an event loop to block the execution (to prevent your program from prematurely terminating): https://github.com/baudm/mplayer.py/wiki/AsyncPlayer
