### ISSUE TITLE
documentation incorrect for Player class

### ISSUE THREAD

**Issue by mikeblas** [baudm/mplayer.py#40]
The docs for the [Player](https://github.com/baudm/mplayer.py/wiki/Player ) suggest importing a class named `CommandPrefix`, but the corrent name is `CmdPrefix`.  Note tthe wrong name is given in 2 different import statements on that page.

**Comment by baudm** [comment]
The documentation clearly states that `CmdPrefix` was previously named `CommandPrefix` in the 0.6.0 release.

**Comment by mikeblas** [comment]
Actually, in one spot, it says "NOTE: In 0.6.0, this was named as command_prefix", lowercase with an underbar.  In another spot, it says "NOTE: In 0.6.0, CmdPrefix is named as CommandPrefix", mixed case with no underbar.

One code example uses "CommandPrefix", another uses "CmdPrefix".

Problem is, the documentation doesn't make it clear what the class is called in present-day builds. Turns out it's "CmdPrefix" and not "CommandPrefix", and also not "command_prefix".
